### PR TITLE
Send plaintext email part in addition to HTML email

### PR DESCRIPTION
**Pull request by dakrone**
There is already a template and generated body from the Mustache template,
might as well use it. Sending text/html and text/plain multipart emails is nice
manners.

### CODE REVIEW

**Comment by drewr** [comment]
IIRC, this didn't look right in Gmail.  Can someone verify?

**Comment by dakrone** [comment]
> IIRC, this didn't look right in Gmail. Can someone verify?

I wasn't sure the best way to test this locally, but if there is a way I'm happy to iterate with the Gmail UI so people don't get upset by it.

**Comment by michaelbaamonde** [comment]
I have a test cluster running locally. I'll deploy a build of this branch there and see how it looks.

**Comment by drewr** [comment]
For future reference:

1. Copy a `runbld.conf` from a slave to your local `/etc/runbld/runbld.conf`.
2. Grab a [reproducibly failing commit](https://goo.gl/8iOxUo) for `elastic+elasticsearch+master`
3. Check out that commit `git checkout -f e88d54bf0aa467d718688eafc5252c1f2021347d`
4. Grab the process source and stick it in a file
```
cat <<EOF >script.sh
gradle --stacktrace clean
gradle --info compileJava compileTestJava precommit check
EOF
```
5. `/path/to/runbld --job-name elastic+elasticsearch+master+multijob-intake script.sh`

**Comment by dakrone** [comment]
@drewr it seems to look good now (and thanks a ton for the help testing @michaelbaamonde!)

**Comment by drewr** [comment]
Thanks @dakrone !

**Comment by dakrone** [comment]
Thanks @drewr!

**Pull request merged**
